server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Use Docker's internal DNS for dynamic resolution 
    # avoids stale IP cache on container restart
    # only valid for 5 seconds, then it will try to resolve again
    # else, it resolves at startup and never updates if the IP changes
    # hence, now even if rebuild and restart container, it will always find the correct IP
    resolver 127.0.0.11 valid=5s;

    location /api/ {
        set $upstream http://api-gateway:8080;
        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
